version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dota_fd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build:
      context: ..
      dockerfile: Dockerfile.backend
    env_file:
      - ../backend/.env.example
    volumes:
      - ../backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  web:
    build:
      context: ..
      dockerfile: Dockerfile.frontend
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - api
volumes:
  db_data:
