name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          pip install --upgrade pip
          pip install black ruff mypy pytest
          pip install -e backend
      - name: Lint & Typecheck
        run: |
          ruff check backend
          black --check backend
          mypy backend
      - name: Test
        run: pytest -q backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and lint
        working-directory: frontend
        run: |
          corepack enable
          corepack prepare pnpm@9.1.0 --activate
          pnpm install
          pnpm run build || true
